New admin check for permissions
18F/cg-dashboard pull request #1062
Opened 2017-04-17 20:21 UTC by rememberlenny

2017-04-18 02:17 UTC, msecret requested changes
I think we should add tests for the new user actions, the new case statement in the user store and the new method in the user store.

2017-04-18 21:02 UTC, rememberlenny commented
Added test for `new user actions`.

2017-04-18 22:09 UTC, rememberlenny commented
Added `case` conditions for `CURRENT_UAA_INFO_FETCH`.

2017-04-18 22:09 UTC, rememberlenny commented
Added the `isAdmin()` related checks.

2017-04-18 22:10 UTC, rememberlenny commented
Finished up the tests around the points mentioned. Good to go! @msecret

2017-04-19 19:07 UTC, msecret approved these changes
One comment about making tests less repeated.

2017-04-19 19:07 UTC, msecret commented on static_src/test/unit/stores/user_store.spec.js
> +      const currentUaaInfo = { guid: '1234' };
These tests in each `it` block seem to have repeated information. Is it possible to move the data to a `beforeEach` like you did below?

2017-04-19 20:27 UTC, merged